### ISSUE TITLE
Build fails on FAIL: test_shifterSpank_prolog

### ISSUE THREAD

**Issue by grod-uy** [NERSC/shifter#191]
Hi, following the instructions [here](https://github.com/NERSC/shifter/blob/master/doc/install/centos7.rst) to build rpms on Centos 7.4.1708 with slurm-17.02.9 installed via rpm (after rpmbuild), I get:
```
make[3]: Entering directory `/root/rpmbuild/BUILD/shifter-16.08.3_2/wlm_integration/slurm/test'
make[4]: Entering directory `/root/rpmbuild/BUILD/shifter-16.08.3_2/wlm_integration/slurm/test'
PASS: test_shifterSpank_config
PASS: test_shifterSpank_util
FAIL: test_shifterSpank_prolog
PASS: test_shifterSpank_cgroup
make[5]: Entering directory `/root/rpmbuild/BUILD/shifter-16.08.3_2/wlm_integration/slurm/test'
make[5]: Nothing to be done for `all'.
make[5]: Leaving directory `/root/rpmbuild/BUILD/shifter-16.08.3_2/wlm_integration/slurm/test'
============================================================================
Testsuite summary for shifter 16.08.3
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See wlm_integration/slurm/test/test-suite.log
Please report to shifter-hpc@googlegroups.com
============================================================================

The contents of test-suite.log:

[root@medusa08 test]# cat test-suite.log
================================================================
   shifter 16.08.3: wlm_integration/slurm/test/test-suite.log
================================================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_shifterSpank_prolog
==============================

MockLogDebug: shifter prolog, id after looking at args: (null):(null)
MockLogDebug: shifter prolog, id after looking at args: local:/
MockLogError: about to lookup image in prolog env
MockLogDebug: shifter prolog, id after looking at env: local:/
MockLogError: Job uid is invalid!

test_shifterSpank_prolog.cpp:36: error: Failure in TEST(shifterSpankPrologGroup, prologInit)
	CHECK(ret == SUCCESS) failed


Errors (1 failures, 1 tests, 1 ran, 2 checks, 0 ignored, 0 filtered out, 1 ms)
```
Any suggestion?, What can I do to fix this?

Thanks

**Comment by dmjacobsen** [comment]
This issue is fixed in the latest release of shifter (and on the master branch).

**Comment by joaovictortr** [comment]
I'm still having the same error using the latest release (either the release or from the master branch).

Platform info:
Distro: CentOS 7.4.1708 x86_64
Compiler: 4.8.5 20150623 (Red Hat 4.8.5-16)
Slurm: 17.11.14 (compiled from source)

Compiling without SLURM causes no errors.

```
================================================================
   shifter 18.03.0: wlm_integration/slurm/test/test-suite.log
================================================================

# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: test_shifterSpank_prolog
==============================

IGNORING parameter autoLoadKernelModule, deprecated.
IGNORING parameter kmodBasePath, deprecated.
IGNORING parameter kmodCacheFile, deprecated.
MockLogDebug: shifter prolog, id after looking at args: (null):(null)
MockLogDebug: shifter prolog, id after looking at args: local:/
MockLogError: about to lookup image in prolog env
MockLogDebug: shifter prolog, id after looking at env: local:/
MockLogError: Job uid is invalid!

test_shifterSpank_prolog.cpp:36: error: Failure in TEST(shifterSpankPrologGroup, prologInit)
        CHECK(ret == SUCCESS) failed

.
Errors (1 failures, 1 tests, 1 ran, 2 checks, 0 ignored, 0 filtered out, 0 ms)
```

**Comment by psykok** [comment]
I  also have the same issue with the last release:

Platform info:
Distro: CentOS 7.4.1708 x86_64
Compiler: GCC 4.8.5 20150623 (Red Hat 4.8.5-16)
Slurm: 17.02.7-1 (compiled from source)


============================================================================
Testsuite summary for shifter 18.03.0
============================================================================
# TOTAL: 4
# PASS:  3
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0
============================================================================
See wlm_integration/slurm/test/test-suite.log
Please report to shifter-hpc@googlegroups.com
============================================================================
make[4]: *** [test-suite.log] Error 1
make[4]: Leaving directory `/usr/src/redhat/BUILD/shifter-18.03.0/wlm_integration/slurm/test'
make[3]: *** [check-TESTS] Error 2
make[3]: Leaving directory `/usr/src/redhat/BUILD/shifter-18.03.0/wlm_integration/slurm/test'
make[2]: *** [check-am] Error 2
make[2]: Leaving directory `/usr/src/redhat/BUILD/shifter-18.03.0/wlm_integration/slurm/test'
make[1]: *** [check-recursive] Error 1
make[1]: Leaving directory `/usr/src/redhat/BUILD/shifter-18.03.0/wlm_integration/slurm'
make: *** [check-recursive] Error 1
error: Bad exit status from /var/tmp/rpm-tmp.M4OPxi (%check)

**Comment by varunnarisetty** [comment]
Were you able to fix this issue? I'm still facing this issue.

**Comment by einjen** [comment]
still have this issue
